"use client";
import { useEffect, useState } from "react";
const PRIORITIES=["low","medium","high"];
function dateValue(v){return v?new Date(v).toISOString().slice(0,10):""}
export default function CardModal({card,members,onClose,onSave,onDelete}){
 const [title,setTitle]=useState(card.title||""); const [description,setDescription]=useState(card.description||""); const [tag,setTag]=useState(card.tag||""); const [priority,setPriority]=useState(card.priority||"medium"); const [dueDate,setDueDate]=useState(dateValue(card.dueDate)); const [assignee,setAssignee]=useState(card.assignee?._id||card.assignee||""); const [items,setItems]=useState((card.checklist||[]).map(x=>({text:x.text,done:!!x.done}))); const [newItem,setNewItem]=useState(""); const [saving,setSaving]=useState(false);
 useEffect(()=>{const f=e=>e.key==="Escape"&&onClose();window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[onClose]);
 async function save(e){e.preventDefault();if(!title.trim())return;setSaving(true);try{await onSave(card._id,{title:title.trim(),description,tag:tag.trim(),priority,dueDate:dueDate||null,assignee:assignee||null,checklist:items.filter(x=>x.text.trim())});onClose()}finally{setSaving(false)}}
 function addItem(e){e.preventDefault();if(!newItem.trim())return;setItems([...items,{text:newItem.trim(),done:false}]);setNewItem("")}
 return <div className="fixed inset-0 z-50 grid place-items-center p-4"><div onClick={onClose} className="absolute inset-0 bg-slate-950/60 backdrop-blur-sm"/><form onSubmit={save} className="relative max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-white/10 bg-white p-6 shadow-2xl animate-modal-in dark:bg-slate-900"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-brand-500">Task workspace</p><h2 className="mt-1 text-xl font-black text-slate-900 dark:text-white">Edit task</h2></div><button type="button" onClick={onClose} className="rounded-xl px-3 py-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">✕</button></div>
 <div className="mt-6 grid gap-5 md:grid-cols-[1.25fr_.75fr]"><div className="space-y-4"><div><label className="label">Title</label><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} className="field"/></div><div><label className="label">Description</label><textarea rows="5" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the outcome, context or acceptance criteria..." className="field resize-none"/></div><div><label className="label">Checklist</label><div className="space-y-2">{items.map((item,i)=><div key={i} className="flex items-center gap-2 rounded-xl border border-slate-200 p-2 dark:border-slate-700"><input type="checkbox" checked={item.done} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,done:e.target.checked}:x))}/><input value={item.text} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,text:e.target.value}:x))} className="min-w-0 flex-1 bg-transparent text-sm outline-none dark:text-white"/><button type="button" onClick={()=>setItems(items.filter((_,j)=>j!==i))} className="text-slate-400 hover:text-rose-500">×</button></div>)}</div><div className="mt-2 flex gap-2"><input value={newItem} onChange={e=>setNewItem(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addItem(e)} placeholder="Add checklist item" className="field"/><button type="button" onClick={addItem} className="button-secondary">Add</button></div></div></div>
 <div className="space-y-4"><div><label className="label">Tag</label><input value={tag} onChange={e=>setTag(e.target.value)} placeholder="design, bug, backend" className="field"/></div><div><label className="label">Priority</label><select value={priority} onChange={e=>setPriority(e.target.value)} className="field">{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select></div><div><label className="label">Due date</label><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="field"/></div><div><label className="label">Assignee</label><select value={assignee} onChange={e=>setAssignee(e.target.value)} className="field"><option value="">Unassigned</option>{members.map(m=><option key={m._id} value={m._id}>{m.name}</option>)}</select></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800/70"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Checklist progress</p><p className="mt-1 text-2xl font-black text-slate-800 dark:text-white">{items.filter(x=>x.done).length}/{items.length}</p><div className="mt-2 h-2 rounded-full bg-slate-200 dark:bg-slate-700"><div className="h-full rounded-full bg-gradient-to-r from-brand-600 to-cyan-500" style={{width:`${items.length?items.filter(x=>x.done).length/items.length*100:0}%`}}/></div></div></div></div>
 <div className="mt-7 flex items-center justify-between gap-3 border-t border-slate-100 pt-5 dark:border-slate-800"><button type="button" onClick={()=>{onDelete(card._id);onClose()}} className="text-sm font-bold text-rose-500">Delete task</button><div className="flex gap-2"><button type="button" onClick={onClose} className="button-secondary">Cancel</button><button disabled={saving} className="button-primary">{saving?"Saving...":"Save changes"}</button></div></div></form></div>
}
