"use client";
import {useEffect,useMemo,useRef,useState} from "react";import {useParams,useRouter} from "next/navigation";import Link from "next/link";import {api,getSessionUser,isLoggedIn} from "../../../lib/api";import {getSocket} from "../../../lib/socket";import {useToasts} from "../../../lib/useToasts";import Column from "../../../components/Column";import PresenceBar from "../../../components/PresenceBar";import DarkModeToggle from "../../../components/DarkModeToggle";import ActivityFeed from "../../../components/ActivityFeed";import CardModal from "../../../components/CardModal";import SearchFilterBar from "../../../components/SearchFilterBar";import ToastStack from "../../../components/Toast";import BoardStats from "../../../components/BoardStats";import MemberPanel from "../../../components/MemberPanel";
export default function BoardPage(){const{id}=useParams();const router=useRouter();const[board,setBoard]=useState(null);const[error,setError]=useState("");const[online,setOnline]=useState([]);const[search,setSearch]=useState("");const[priority,setPriority]=useState("");const[assignee,setAssignee]=useState("");const[sort,setSort]=useState("board");const[addCol,setAddCol]=useState(false);const[colName,setColName]=useState("");const[invite,setInvite]=useState(false);const[email,setEmail]=useState("");const[inviteMsg,setInviteMsg]=useState("");const[activity,setActivity]=useState(false);const[membersOpen,setMembersOpen]=useState(false);const[editing,setEditing]=useState(null);const[exiting,setExiting]=useState(new Set());const drag=useRef(null);const input=useRef(null);const session=useRef(getSessionUser());const{toasts,push,dismiss}=useToasts();
 useEffect(()=>{if(!isLoggedIn()){router.replace('/login');return}let active=true;api.getBoard(id).then(d=>active&&setBoard(d.board)).catch(e=>active&&setError(e.message));const s=getSocket();s.connect();s.emit('join-board',{boardId:id,user:session.current});s.on('board:update',b=>b._id===id&&setBoard(b));s.on('presence:update',setOnline);return()=>{active=false;s.off('board:update');s.off('presence:update');s.disconnect()}},[id,router]);
 useEffect(()=>{const f=e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if(e.key==='/'&&!typing){e.preventDefault();input.current?.focus()}if(e.key==='Escape'&&typing)document.activeElement.blur()};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
 const members=useMemo(()=>{if(!board)return[];const list=[board.owner,...(board.members||[])].filter(Boolean);const seen=new Set();return list.filter(m=>{const k=m._id||m;if(seen.has(String(k)))return false;seen.add(String(k));return true})},[board]);
 const filtered=useMemo(()=>{if(!board)return[];const q=search.trim().toLowerCase();return board.columns.slice().sort((a,b)=>a.order-b.order).map(column=>{let cards=column.cards.slice();cards=cards.filter(c=>(!q||(c.title+' '+(c.description||'')+' '+(c.tag||'')).toLowerCase().includes(q))&&(!priority||c.priority===priority)&&(!assignee||c.assignee?._id===assignee));if(sort==='priority')cards.sort((a,b)=>({high:0,medium:1,low:2}[a.priority]-({high:0,medium:1,low:2}[b.priority])));if(sort==='due')cards.sort((a,b)=>(a.dueDate?new Date(a.dueDate):new Date('2999'))-(b.dueDate?new Date(b.dueDate):new Date('2999')));if(sort==='title')cards.sort((a,b)=>a.title.localeCompare(b.title));return{column,cards,totalCardCount:column.cards.length}})},[board,search,priority,assignee,sort]);
 const stats=useMemo(()=>{const cards=board?.columns?.flatMap(c=>c.cards)||[];const done=board?.columns?.filter(c=>/done|complete/i.test(c.name)).reduce((n,c)=>n+c.cards.length,0)||0;return{total:cards.length,done,high:cards.filter(c=>c.priority==='high').length}},[board]);
 function dragStart(e,cardId,columnId){drag.current={cardId,fromColumnId:columnId};e.dataTransfer.effectAllowed='move'} async function drop(e,toColumnId,toIndex){e.preventDefault();e.stopPropagation();const d=drag.current;drag.current=null;if(!d)return;try{await api.moveCard(id,d.cardId,{toColumnId,toIndex})}catch(e){setError(e.message)}}
 async function act(fn){try{setError('');await fn()}catch(e){setError(e.message)}}
 async function addCard(columnId,payload){await act(()=>api.addCard(id,columnId,payload))} async function updateCard(cardId,payload){await act(()=>api.updateCard(id,cardId,payload))} function delCard(cardId){setExiting(x=>new Set(x).add(cardId));setTimeout(()=>act(()=>api.deleteCard(id,cardId)).finally(()=>setExiting(x=>{const n=new Set(x);n.delete(cardId);return n})),160)}
 async function addColumn(e){e.preventDefault();if(!colName.trim())return;await act(()=>api.addColumn(id,colName.trim()));setColName('');setAddCol(false)} async function rename(c,n){await act(()=>api.renameColumn(id,c,n))} async function delColumn(c){if(!confirm('Delete this column and its tasks?'))return;await act(()=>api.deleteColumn(id,c))}
 async function inviteMember(e){e.preventDefault();setInviteMsg('');try{await api.inviteMember(id,email.trim());setInviteMsg('Member added successfully.');setEmail('')}catch(e){setInviteMsg(e.message)}} async function removeMember(mid){if(!confirm('Remove this member?'))return;await act(()=>api.removeMember(id,mid))}
 async function renameBoard(){const n=prompt('Rename board',board.name);if(n&&n.trim()!==board.name)await act(()=>api.updateBoard(id,{name:n.trim()}))} async function deleteBoard(){if(!confirm('Delete this board permanently?'))return;await act(async()=>{await api.deleteBoard(id);router.replace('/dashboard')})} async function leave(){if(!confirm('Leave this board?'))return;await act(async()=>{await api.leaveBoard(id);router.replace('/dashboard')})}
 if(error&&!board)return <main className="grid min-h-screen place-items-center p-6"><div className="max-w-md rounded-3xl border border-rose-200 bg-white p-8 text-center shadow-xl dark:border-rose-900/50 dark:bg-slate-900"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-rose-50 text-2xl text-rose-500 dark:bg-rose-500/10">!</div><h1 className="mt-5 text-xl font-black text-slate-800 dark:text-white">Board access problem</h1><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{error}</p><Link href="/dashboard" className="mt-5 inline-flex button-primary">Back to dashboard</Link></div></main>;
 if(!board)return <main className="grid min-h-screen place-items-center"><div className="text-sm font-semibold text-slate-400 animate-pulse">Loading your workspace...</div></main>;
 const ownerId=board.owner?._id||board.owner;const currentId=session.current?.id||session.current?._id;const owner=String(ownerId)===String(currentId);
 return <main className="min-h-screen px-3 py-4 sm:px-5"><div className="mx-auto max-w-[1500px]"><header className="glass card-shadow sticky top-3 z-30 mb-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl px-3 py-3"><div className="flex min-w-0 items-center gap-3"><Link href="/dashboard" className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-brand-600 to-cyan-500 font-black text-white">TS</Link><div className="min-w-0"><div className="flex items-center gap-2"><h1 className="truncate text-lg font-black text-slate-800 dark:text-white">{board.name}</h1><button onClick={renameBoard} className="rounded-lg px-2 text-xs text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800">✎</button></div><p className="text-[11px] font-semibold text-slate-400">{stats.total} tasks · {stats.done} completed · {members.length} members</p></div></div><div className="flex items-center gap-2"><PresenceBar users={online}/><button onClick={()=>setMembersOpen(v=>!v)} className="button-secondary">Team</button><button onClick={()=>setActivity(true)} className="button-secondary">Activity</button><button onClick={()=>setInvite(v=>!v)} className="button-secondary">+ Invite</button><DarkModeToggle/><button onClick={owner?deleteBoard:leave} className="rounded-xl border border-rose-200 px-3 py-2 text-sm font-bold text-rose-500 hover:bg-rose-50 dark:border-rose-900/50 dark:hover:bg-rose-500/10">{owner?'Delete':'Leave'}</button></div></header>
 <BoardStats board={board}/>
 {invite&&<div className="mb-4 animate-fade-in rounded-2xl border border-brand-100 bg-white p-4 card-shadow dark:border-brand-900/40 dark:bg-slate-900"><form onSubmit={inviteMember} className="flex flex-col gap-2 sm:flex-row"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Teammate email address" className="field flex-1"/><button className="button-primary">Invite member</button></form>{inviteMsg&&<p className="mt-2 text-xs font-semibold text-slate-500">{inviteMsg}</p>}</div>}
 {membersOpen&&<div className="mb-4 max-w-xl animate-panel-in"><MemberPanel members={members} owner={ownerId} currentUserId={currentId} onRemove={removeMember}/></div>}
 <div className="mb-4 flex flex-col gap-2 lg:flex-row"><div className="min-w-0 flex-1"><SearchFilterBar ref={input} query={search} onQueryChange={setSearch} priority={priority} onPriorityChange={setPriority} assignee={assignee} onAssigneeChange={setAssignee} members={members}/></div><select value={sort} onChange={e=>setSort(e.target.value)} className="field h-10 w-full lg:mt-0 lg:w-44"><option value="board">Sort: Board order</option><option value="priority">Sort: Priority</option><option value="due">Sort: Due date</option><option value="title">Sort: Title</option></select></div>
 {error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-600 dark:border-rose-900/50 dark:bg-rose-500/10">{error}</div>}
 <div className="board-scroll flex gap-4 overflow-x-auto pb-6">{filtered.map(({column,cards,totalCardCount})=><Column key={column._id} column={column} cards={cards.map(c=>({...c,exiting:exiting.has(c._id)}))} totalCardCount={totalCardCount} onDragStart={dragStart} onDrop={drop} onDelete={delCard} onAddCard={addCard} onOpenCard={setEditing} onRenameColumn={rename} onDeleteColumn={delColumn}/>)}<div className="min-w-[280px] flex-1">{addCol?<form onSubmit={addColumn} className="rounded-2xl bg-white p-4 card-shadow dark:bg-slate-900"><input autoFocus value={colName} onChange={e=>setColName(e.target.value)} placeholder="Column name" className="field"/><div className="mt-3 flex gap-2"><button className="button-primary">Add column</button><button type="button" onClick={()=>setAddCol(false)} className="button-secondary">Cancel</button></div></form>:<button onClick={()=>setAddCol(true)} className="flex min-h-24 w-full items-center justify-center rounded-2xl border-2 border-dashed border-slate-300 text-sm font-bold text-slate-400 transition hover:border-brand-400 hover:bg-brand-50/40 hover:text-brand-600 dark:border-slate-700 dark:hover:bg-brand-500/5">+ Add workflow column</button>}</div></div>
 <ActivityFeed open={activity} onClose={()=>setActivity(false)} activity={board.activity}/>{editing&&<CardModal card={editing} members={members} onClose={()=>setEditing(null)} onSave={updateCard} onDelete={delCard}/>}<ToastStack toasts={toasts} onDismiss={dismiss}/></div></main>
}
